### ISSUE TITLE
400 and 401 errors - refresh tokens

### ISSUE THREAD

**Issue by klaaskox** [picqer/exact-php-client#300]
We have been using this library for a couple of years, and all is working fine. However, now I am getting 400 and 401 errors (**Could not connect to Exact: Could not acquire or refresh tokens [http 401]**).

I now found an email from exact some weeks ago stating 

> You receive this e-mail since our logging shows that your application, linked to Exact Online, is using old refresh tokens in order to connect to Exact Online. 

> As per the 30th of September it will not be possible anymore to re-use a refresh token more than once. 

I thought the picqer Connection library wold automatically use the refresh tokens.

Until today the API had been working just fine, but now I am getting these errors. Has anybody any idea what I can do to fix this? Thanks!

**Comment by hugovandepol** [comment]
Same issue here. Untill today everything was working fine. I'm getting this error:

Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `401 Unauthorized` response: {"error":"unauthorized_client","error_description":"Old refresh token used."}

Anyone any ideas? I'm looking into it myself as well.

**Comment by ovvessem** [comment]
‘Glad’ to see that @klaaskox and @hugovandepol are having the same issue as I have since this afternoon. I will also look more in-depth since this repo is an important part in our internal integration.

**Comment by MHermsen** [comment]
The refresh token you need to get a new code... seems the refresh code is the old refresh token...
Maybe its more intresting which version from the Exact PHP client is used...... I am using still PHP 5.6 and use not the newer Exact PHP Client 3.x.x which is only for PHP 7..   Everything works fine till now

**Comment by klaaskox** [comment]
I am also still running PHP 5.6. Has anybody received a similar email from Exact about the refresh token +- 1 month ago?

**Comment by StefanoGroenland** [comment]
Same error here since yesterday, two high traffic webapplications used to run smoothly, but since yesterday our error reporting application (Sentry) gets filled with old refresh token errors.

**Comment by flowan** [comment]
I have the exact same issue. Not sure how to fix this issue:
`{"error":"unauthorized_client","error_description":"Old refresh token used."}`

**Comment by Jelle90** [comment]
Same issue here. Currently trying to find a solution.

**Comment by stephangroen** [comment]
Haven't had this issue yet. Do you save both access and request tokens every time you create a new connection?

**Comment by stephangroen** [comment]
That's about the same flow I use. Everytime after the `connect()` call I save the refresh and accesstokens. I do also save the `expires_in` and  set this in the client, so the client first gets a new token if expires in is no longer valid. So that would be something like this:

```php
        $connection = new Connection();
        $connection->setBaseUrl($this->getApiUrl());
        $connection->setRedirectUrl(/** config data **/);
        $connection->setExactClientId(/** config data **/);
        $connection->setExactClientSecret(/** config data **/);

        $connection->setAuthorizationCode(/** config data **/);
        $connection->setAccessToken(/** config data **/);
        $connection->setRefreshToken(/** config data **/);
        $connection->setTokenExpires(/** config data **/);

        $connection->connect();

        $this->saveTokens($connection); // saves authcode, accesstoken, refreshtoken and expires
```

**Comment by ovvessem** [comment]
I am using the Laravel wrapper from [PendoNL](https://github.com/PendoNL/laravel-exact-online) which uses the same structure as mentioned above. The access and request tokens with the expires_in value get stored in a json file. The file itself refreshed after each connect.

**Comment by StefanoGroenland** [comment]
@stephangroen 

I used to do : 
```
try {
            $this->connection->setRefreshToken($account->refresh_token);
            $this->connection->setAccessToken($account->access_token);
            $this->connection->setAuthorizationCode($account->authorization_code);
            $this->connection->setTokenExpires($account->token_expire->timestamp);
            $this->connection->connect();
        } catch (\Exception $e) {
            throw new \Exception('Could not connect to Exact ' . $e->getMessage());
        }

        if ($account->token_expire === null || $account->token_expire->isPast()) {
            $account->update([
                'access_token' => $this->connection->getAccessToken(),
                'refresh_token' => $this->connection->getRefreshToken(),
                'token_expire' => Carbon::createFromTimestamp($this->connection->getTokenExpires())
            ]);
        }
```

But the above results in the same error aswel, and since the refresh token is only valid once the code without the `TokenExpires` is the latest i use.

**Comment by stephangroen** [comment]
Hmmm, I cannot make up another reason for why the token should be outdated/invalid. Are you perhaps using this code in background jobs with multiple workers where one worker could refresh the token and another could still have the old token?

**Comment by StefanoGroenland** [comment]
> Hmmm, I cannot make up another reason for why the token should be outdated/invalid. Are you perhaps using this code in background jobs with multiple workers where one worker could refresh the token and another could still have the old token?

I am in fact using that, But all jobs first create their connection before doing anything else. So i think that the connection gets "snapshotted" in the job so the token should be valid for that request in my opinion. What do you think about this @stephangroen ?

**Comment by StefanoGroenland** [comment]
The way i described in https://github.com/picqer/exact-php-client/issues/300#issuecomment-430546548 is the way i have run for aprox. 7 months without issues.

**Comment by klaaskox** [comment]
Now everything seems to be working fine again. I did not change anything. Can anybody confirm this?

**Comment by StefanoGroenland** [comment]
I haven't received any new errors, so i guess they fixed something..

**Comment by MHermsen** [comment]
Maybe Exact did some wrong !

**Comment by hugovandepol** [comment]
Same here. I didn't change any code and didn't get any new errors today.

**Comment by StefanoGroenland** [comment]
I added a fallback which i suggest you guys do to, to prevent the use of old refresh tokens!

   ```
        try {
            $this->connection->setAccessToken($account->access_token);
            $this->connection->setRefreshToken($account->refresh_token);
            $this->connection->setAuthorizationCode($account->authorization_code);
            $this->connection->connect();
        } catch (RequestException $e) {
            $this->connection->setAccessToken(null);
            $this->connection->setRefreshToken(null);
            $this->connection->connect();
        } catch (\Exception $e) {
            throw new \Exception('Could not connect to Exact ' . $e->getMessage());
        }
```

When there is no `AccessToken` AND no `RefreshToken` the `connect()` function 
will run inside the following statement :
```
        // If access token is not set or token has expired, acquire new token
        if (empty($this->accessToken) || $this->tokenHasExpired()) {
            $this->acquireAccessToken();
        }
```

**Comment by stephangroen** [comment]
Let's keep this open for now to check if anyone still has any problems. Thanks for sharing your findings everyone :-)

**Comment by StefanoGroenland** [comment]
Just received an message from ExactOnline about this matter.

```
On October 16 Exact Online has the possibility to reuse old refresh tokens, as planned, deactivated.
If you wanted to request an access token with an already used refresh token on this day, you received a "401 - Unauthorized" error message.
 
Even though it was emailed exactly here in August, it appeared that there were still a large number of applications that could not implement this adjustment in time.
At this moment we have reversed this adjustment so that already used refresh tokens can be used again.
 
We are now looking at what the next step will be to ensure that all applications will meet the non-reuse of refresh tokens.
You can expect more information from us on this subject in the coming weeks, until that time you can continue to reuse the refresh tokens.
 
For the applications that do not currently use refresh tokens (and therefore have made the necessary changes in time), we will already ensure that old tokens can no longer be reused to ensure that the end-user is as secure as possible.
```

**Comment by tomcoonen** [comment]
That's weird, I never got a notice they would disable this.
Implementing a fix now anyways :)

**Comment by DaveyGiesen** [comment]
We had the same problem also yesterday. Just reauthorize and now everything is working.

**Comment by ovvessem** [comment]
@StefanoGroenland would you care to share your implementation in a gist?

**Comment by StefanoGroenland** [comment]
> That's weird, I never got a notice they would disable this.
> Implementing a fix now anyways :)

Me neither @tomcoonen 

> We had the same problem yesterday. Just reauthorize and now everything is working.
That only helped me get past a few requests for like 5 minutes then i had to re-authenticate again.

**Comment by StefanoGroenland** [comment]
> @StefanoGroenland would you care to share your implementation in a gist?

Sure, i have created 2 classes for initializing the connection, you can see them here : https://gist.github.com/StefanoGroenland/5046012555c9c232aa38a073365bbbb0

**Comment by alexjeen** [comment]
This seems to be an issue on the Exact side. We never reuse refresh tokens (it's impossible in our code flows) but still we got these errors.

It's working fine now.

**Comment by StefanoGroenland** [comment]
Just received this in the mail.

![image](https://user-images.githubusercontent.com/6575921/48061552-a0592500-e1bf-11e8-86cf-cf0eccf1e751.png)

Link 1 : https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Landing-appcenter-eol-appcenter-dev-tlsprotocol

Link 2 : https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-step4

**Comment by it-can** [comment]
just got this email from Exact


```
You receive this e-mail since our logging shows that your application, linked to Exact Online, is using old refresh tokens in order to connect to Exact Online. If you are not the supplier or developer of the application, please send this message as soon as possible to your supplier or developer of this application. As per the 31st of December it will not be possible anymore to re-use a refresh token more than once. Every time your application requests a new access token, using a refresh token, alongside that refresh token, you are also granted a new refresh token. This new refresh token has always been intended for applications to retrieve new access with, this way applications can maintain their high security standards. The complete flow of how  access and refresh tokens should be used is described in step 4 of our OAuth tutorial, please see: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-step4 Make sure these changes are applied before the 31st of December as from that date, the application will not be able exchange data with Exact Online if it still uses old refresh tokens. |   | You receive this e-mail since our logging shows that your application, linked to Exact Online, is using old refresh tokens in order to connect to Exact Online. If you are not the supplier or developer of the application, please send this message as soon as possible to your supplier or developer of this application. As per the 31st of December it will not be possible anymore to re-use a refresh token more than once. Every time your application requests a new access token, using a refresh token, alongside that refresh token, you are also granted a new refresh token. This new refresh token has always been intended for applications to retrieve new access with, this way applications can maintain their high security standards. The complete flow of how  access and refresh tokens should be used is described in step 4 of our OAuth tutorial, please see: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-step4 Make sure these changes are applied before the 31st of December as from that date, the application will not be able exchange data with Exact Online if it still uses old refresh tokens.
-- | -- | --
 
You receive this e-mail since our logging shows that your application, linked to Exact Online, is using old refresh tokens in order to connect to Exact Online. If you are not the supplier or developer of the application, please send this message as soon as possible to your supplier or developer of this application. As per the 31st of December it will not be possible anymore to re-use a refresh token more than once. Every time your application requests a new access token, using a refresh token, alongside that refresh token, you are also granted a new refresh token. This new refresh token has always been intended for applications to retrieve new access with, this way applications can maintain their high security standards. The complete flow of how  access and refresh tokens should be used is described in step 4 of our OAuth tutorial, please see: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-dev-step4 Make sure these changes are applied before the 31st of December as from that date, the application will not be able exchange data with Exact Online if it still uses old refresh tokens.


```

**Comment by klaaskox** [comment]
I received the same e-mail (subject: "REMINDER: SERVICE MESSAGE - OLD REFRESH TOKENS") a couple of days ago, so I guess this means the problem is still there. I hoped the issues we had mid-October were caused by issues on the Exact-side. Did everybody receive this mail, or does anybody know what we can do to solve this problem?

**Comment by klaaskox** [comment]
I contacted Exact, and asked them if they could send me some logging of the token-usage. They told me they could not send me any logging, except from the daily stats. For example, yesterday:
- 51 x correct token
- 162 x old refresh token

Anyone any ideas what could cause this?

**Comment by herrwalter** [comment]
I'm also looking for a fix on this problem. We are getting the 401 in about 5 times per day. 
Anyone got this problem fixed?

**Comment by klaaskox** [comment]
A part of our problem was caused by multiple cronjobs starting at the same time which results in a problem when the token needs to be refreshed. We fixed this with a locking mechanism that makes sure there is only one process starting a connection to EO at the same time. The other processes must wait until the first one is connected to EO.

**Comment by StefanoGroenland** [comment]
@klaaskox do you use Laravel with Queue-ing by any chance? I do, and i still get those 400 errors time to time, even when i am refreshing the token on every job.

**Comment by herrwalter** [comment]
@StefanoGroenland @klaaskox 
We use the Queueing as well and we still get 400reds.
Same problem here.

**Comment by klaaskox** [comment]
I use a simple php locking mechanism that locks a file before connecting to EO. After connecting it unlocks the file. Before a process can connect to EO it checks if the file is locked, if so it waits a couple of seconds and checks again.

I have limited the number of times a process can check the lockfile to connect to EO. If it reaches the limit, it stops and logs the failure. This almost never occurs, but this morning the problem occurred two times, probably due to slow connections.

**Comment by StefanoGroenland** [comment]
@klaaskox that's possible. there were some performance issues this morning.

**Comment by stephangroen** [comment]
Is this issue resolved by using locking to get a refresh token and preventing multiple processes to simultaneously try to get a new refresh token? We already had this process locked so I cannot easily verify. There are no known issues on our side.

**Comment by ksbomj** [comment]
Hi guys,

I didn't get, how it's possible to make exact client working. According to the docs I do everything correctly but in 10 mins, **refresh_token** is expired so how to generate new tokens automatically?

**Comment by fredattack** [comment]
> Hi guys,
> 
> I didn't get, how it's possible to make exact client working. According to the docs I do everything correctly but in 10 mins, **refresh_token** is expired so how to generate new tokens automatically?

I have exactly the same probleme, did you find a solution?

**Comment by stephangroen** [comment]
The client will to this for you if you follow the example and store the tokens.

**Comment by jeffreyT836** [comment]
I don't know is this topic is still active, but I'm using the laravel wrapper and get an 400 error that it could not obtain the refreshtoken. 
After dumping the $config it seems that the json respons only has the exact_authorisationCode and the rest is null. 

Does anyone has some suggestions?

**Comment by paddotk** [comment]
As of August 2020 I regularly get this issue, in an application that doesn't use exact-php-client or php at all. Must be an issue with Exact.

**Comment by sjoerdmaessen** [comment]
Having issues aswell since 1-2 weeks. 

`[Exception]                                                                                                   
  Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response:  
  {"error":"invalid_request","error_description":"Signed data extraction has failed"}                           
   - Could not connect to Exact: Could not acquire or refresh tokens [http 400] 0`

**Comment by markjongkind** [comment]
I had a VARCHAR limit of 900 characters in my database scheme and found out the access tokens and refresh tokens are now longer strings than before (906 characters, for example). This started on July 30 in my case. Because of the character limit in the database, the access tokens where saved incomplete and didn't worked.

Hope this insight helps someone, but I'm not sure if it's related to the issues above.

**Comment by Codmic** [comment]
We also have this issue. What I can see is that our command line task which wants to refresh can't refresh the token even before the token expires. See my system date and time in the right corner. I think this is some timing issue where the token expires before the given date says.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/23095651/92138013-27a06f80-ee0e-11ea-909f-fd5b0fdb5214.png">

**Comment by harveencensus** [comment]
I get this error sometimes. This is my code. Can someone review it or show me a working example code.
`<?php

namespace App\Exact;

use App\Models\Exact;
use App\Models\Match;
use App\Models\Package;
use App\Models\ProfBudget;
use App\Models\Professional;
use App\Models\Transaction;
use Carbon\Carbon;
use GuzzleHttp\Client;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Picqer\Financials\Exact\Account;
use Picqer\Financials\Exact\Bank;
use Picqer\Financials\Exact\Connection;
use Picqer\Financials\Exact\DocumentAttachment;
use Picqer\Financials\Exact\Item;
use Picqer\Financials\Exact\PrintedSalesInvoice;
use Picqer\Financials\Exact\SalesInvoice;
use Picqer\Financials\Exact\SalesInvoiceLine;

class ExactOnline
{
    protected $client;
    protected $exact;
    protected $connection;
    protected $exact_client;

    public function __construct($setup = true)
    {
        $this->client = new Client();
        $this->exact = Exact::latest('id')->first();
        if($setup)
        {
            $this->setup();
        }
    }

    public function setup()
    {
        $this->connection = new Connection();
        $this->connection->setRedirectUrl(config('exact.callback'));
        $this->connection->setExactClientId(config('exact.client.id'));
        $this->connection->setExactClientSecret(config('exact.client.secret'));
        if($this->getCode())
        {
            $this->connection->setAuthorizationCode($this->getCode());
        }
        $this->connection->setAccessToken($this->getAccessToken());
        $this->connection->setRefreshToken($this->getRefreshToken());
        $this->connection->setTokenExpires($this->getExpiresIn());
        $this->connection->setTokenUpdateCallback("App\Exact\ExactOnline::tokenUpdateCallback");
        $this->exact_client = $this->connection->connect();

        $this->exact->refresh_token = $this->connection->getRefreshToken();
        $this->exact->access_token = $this->connection->getAccessToken();
        $this->exact->save();

    }

    public function getCode()
    {
        return $this->exact->code;
    }

    public function getToken($code)
    {
        $response = $this->client->post(config('exact.oauth.token.url'),[
            'form_params' => [
                'grant_type' => 'authorization_code',
                'code' => $code,
                'client_id' => config('exact.client.id'),
                'client_secret' => config('exact.client.secret'),
                'redirect_uri' => config('exact.callback')
            ]
        ]);

        return $response;
    }

    public function refreshToken()
    {
        $this->exact = Exact::latest('id')->first();
        $response = $this->client->post(config('exact.oauth.token.url'),[
            'headers' => ['Content-Type' => 'application/x-www-form-urlencoded'],
            'form_params' => [
                'refresh_token' => $this->exact->refresh_token,
                'grant_type' => 'refresh_token',
                'client_id' => config('exact.client.id'),
                'client_secret' => config('exact.client.secret')
            ]
        ]);

        return $response;
    }

    public function getRefreshToken()
    {
        return $this->exact->refresh_token;
    }

    public function getAccessToken()
    {
        return $this->exact->access_token;
    }

    public function getExpiresIn()
    {
        return Carbon::parse($this->exact->next_update)->subSeconds(10)->timestamp;
    }

    public function validate($data)
    {
        $check = Validator::make($data, [
            'access_token' => 'required',
            'token_type' => 'required',
            'expires_in' => 'required',
            'refresh_token' => 'required'
        ]);

        if($check->failed())
        {
            throw new \Exception("Validation failed");
        }

        return true;
    }

    public function createDebtor($professional)
    {
    }

    public function updateDebtor(Professional $professional)
    {
    }

    public function createInvoice($professional)
    {
    }

    public function createInvoiceFile($id)
    {
    }


    public static function tokenUpdateCallback(Connection $connection)
    {
    }

    public function createBank($professional)
    {
    }

    public function getInvoices($id)
    {
    }

    public function getInvoiceLines($InvoiceID)
    {
    }

    public function getInvoiceFile($id, $professional)
    {
    }
}
`

**Comment by Timdenouden1** [comment]
Ok, I have the same error as sjoerdmaessen.
I use the latest version of this exact-api-client (3.24.0)
When I look at the  [Exact Online Developer documentation](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-respcodeserrorhandling)
it states: 

400 | Bad Request | This error occurs when the request could not be understood by the server due to malformed syntax. The client should not repeat the request without modifications.
-- | -- | --

The error clearly comes from Exact, but what is wrong with the request made?
What does this mean: "Signed data extraction has failed"
Is it, maybe, because I dont use an encrypted endpoint, as redirectURL?
Or is something missing in the: acquireAccessToken() function?

**Comment by Eligioo** [comment]
For people reading this after a long time. I also received this error when I accidentally used an authorization code from Exact Online Germany in Exact Online Netherlands.
